version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --offline
      - run:
          # Helps to speed up some of the tests that we have
          name: Build packages
          command: yarn build
      - run:
          name: Run ci checks
          command: yarn ci-check
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
