version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio:3.6.0
    ports:
      - "4873:4873"
    volumes:
      - verdaccio:/verdaccio

  test:
    build:
      context: ../
      dockerfile: ./e2e/Dockerfile
    depends_on:
      - verdaccio

volumes:
  verdaccio:
    driver: local
